### ISSUE TITLE
Pysam error with datasetWhitelist.py script

### ISSUE THREAD

**Issue by MarisaMiller** [PacificBiosciences/apps-scripts#1]
Hello,

I am using this script to whitelist a subset of RSII reads. What I did was the following:

-Import RS II data with pbservice import-rs-movie.
-Convert to BAM via gui
-Take the file.subreadset.xml file produced by the conversion and use the whitelisting script on it (this is where the error is occurring)
-Next, I plan to import the whitelisted subreadset.xml file using pbservice import-dataset

I got through steps 1 and 2 just fine, but now I'm trying to whitelist the subreadset.xml file and am encountering a python error that appears to be related to pysam (see below). 

FYI, I'm using the Enthought Python Distribution (2.7) and installed pbcore in my own directory on our cluster here at MSI (Minnesota Supercomputing Institute) and not system wide.

-Marisa

```
Traceback (most recent call last):
  File "datasetWhitelist.py", line 52, in <module>
    main(parser)
  File "datasetWhitelist.py", line 16, in main
    dset.addFilters(filt)
  File "/home/kianians/millerme/.local/lib/python2.7/site-packages/pbcore-1.4.0-py2.7.egg/pbcore/io/dataset/DataSetIO.py", line 1328, in addFilters
    self.reFilter(light=underConstruction)
  File "/home/kianians/millerme/.local/lib/python2.7/site-packages/pbcore-1.4.0-py2.7.egg/pbcore/io/dataset/DataSetIO.py", line 1725, in reFilter
    self.updateCounts()
  File "/home/kianians/millerme/.local/lib/python2.7/site-packages/pbcore-1.4.0-py2.7.egg/pbcore/io/dataset/DataSetIO.py", line 2488, in updateCounts
    self.assertIndexed()
  File "/home/kianians/millerme/.local/lib/python2.7/site-packages/pbcore-1.4.0-py2.7.egg/pbcore/io/dataset/DataSetIO.py", line 2318, in assertIndexed
    self._assertIndexed((IndexedBamReader, CmpH5Reader))
  File "/home/kianians/millerme/.local/lib/python2.7/site-packages/pbcore-1.4.0-py2.7.egg/pbcore/io/dataset/DataSetIO.py", line 1891, in _assertIndexed
    self._openFiles()
  File "/home/kianians/millerme/.local/lib/python2.7/site-packages/pbcore-1.4.0-py2.7.egg/pbcore/io/dataset/DataSetIO.py", line 2015, in _openFiles
    resource = IndexedBamReader(location)
  File "/home/kianians/millerme/.local/lib/python2.7/site-packages/pbcore-1.4.0-py2.7.egg/pbcore/io/align/BamIO.py", line 385, in __init__
    super(IndexedBamReader, self).__init__(fname, referenceFastaFname)
  File "/home/kianians/millerme/.local/lib/python2.7/site-packages/pbcore-1.4.0-py2.7.egg/pbcore/io/align/BamIO.py", line 196, in __init__
    self._checkFileCompatibility()
  File "/home/kianians/millerme/.local/lib/python2.7/site-packages/pbcore-1.4.0-py2.7.egg/pbcore/io/align/BamIO.py", line 185, in _checkFileCompatibility
    checkedVersion = self.version
  File "/home/kianians/millerme/.local/lib/python2.7/site-packages/pbcore-1.4.0-py2.7.egg/pbcore/io/align/BamIO.py", line 271, in version
    return self.peer.header["HD"]["pb"]
  File "pysam/calignmentfile.pyx", line 1258, in pysam.calignmentfile.AlignmentFile.header.__get__ (pysam/calignmentfile.c:15426)
ValueError: unknown field code 'PM' in record 'RG'
```

**Comment by jrharting** [comment]
Hi Marisa,

Thanks for this comment -- can you prodive me with the version of pysam you have installed with your enthought python distribution?

Thanks,
John

**Comment by MarisaMiller** [comment]
Hi John,

I just checked and it looks like it's version 0.8.3 that's installed system-wide. I updated my $PYTHONPATH and now when I run `pip show pysam` I am using version 0.10.0 that I installed in my own directory.

I re-ran the whitelisting script and now I'm getting a different error (See below). Any ideas what could cause this one?

Thanks,
Marisa


```
Traceback (most recent call last):
  File "datasetWhitelist.py", line 52, in <module>
    main(parser)
  File "datasetWhitelist.py", line 16, in main
    dset.addFilters(filt)
  File "/home/kianians/millerme/.local/lib/python2.7/site-packages/pbcore-1.4.0-py2.7.egg/pbcore/io/dataset/DataSetIO.py", line 1328, in addFilters
    self.reFilter(light=underConstruction)
  File "/home/kianians/millerme/.local/lib/python2.7/site-packages/pbcore-1.4.0-py2.7.egg/pbcore/io/dataset/DataSetIO.py", line 1725, in reFilter
    self.updateCounts()
  File "/home/kianians/millerme/.local/lib/python2.7/site-packages/pbcore-1.4.0-py2.7.egg/pbcore/io/dataset/DataSetIO.py", line 2490, in updateCounts
    numRecords, totalLength = self._length
  File "/home/kianians/millerme/.local/lib/python2.7/site-packages/pbcore-1.4.0-py2.7.egg/pbcore/io/dataset/DataSetIO.py", line 2409, in _length
    count = len(self.index)
  File "/home/kianians/millerme/.local/lib/python2.7/site-packages/pbcore-1.4.0-py2.7.egg/pbcore/io/dataset/DataSetIO.py", line 1876, in index
    self._index = self._indexRecords()
  File "/home/kianians/millerme/.local/lib/python2.7/site-packages/pbcore-1.4.0-py2.7.egg/pbcore/io/dataset/DataSetIO.py", line 2379, in _indexRecords
    self.movieIds)
  File "/home/kianians/millerme/.local/lib/python2.7/site-packages/pbcore-1.4.0-py2.7.egg/pbcore/io/dataset/DataSetMembers.py", line 806, in filterIndexRecords
    movie, hole, span = value.split('/')
ValueError: need more than 2 values to unpack
```

**Comment by jrharting** [comment]
Hi Marisa,
What are you using as input to the whitelisting script?  It is a list or a fasta?  This error is because it is looking for a read name with three fields, separated by '/'.  The expected read naming format is something like:
 <movie>/<holenumber>/<qstart_qend>
m170102_235117_00114_c101046252550000001823265912031640_s1_p0/1234/0_1234

**Comment by jrharting** [comment]
sorry, the markup removed some of that text, ignore the line with qstart_qend

**Comment by MarisaMiller** [comment]
Hi John,

It is a list and the format is like this: m160616_190235_00122_c101001102550000001823239409161693_s1_p0/100060

-Marisa

**Comment by jrharting** [comment]
did you use the --subreads option?

**Comment by MarisaMiller** [comment]
I did, the command I used was the following: `python datasetWhitelist.py -o org_data_mt_filtered.xml -s -l $SSET ORG_whitelist.txt`

**Comment by jrharting** [comment]
The subread option will only work if you are passing a list of subread names, and subread names are defined as having all three fields (  moviename/holenumber/qstart_qend ), where the last field defines the *sub*read region within the continuous read from the sequencing hole.  (here is a good graphic http://pacbiofileformats.readthedocs.io/en/3.0/Primer.html).

If your list includes just movename/holenumber, then you should remove the '-s' option -- this will whitelist the whole zmw.  For the typical case, this is usually what you want -- because all subreads from a zmw are from the same molecule, they are essentially replicates of the same sequence.  

If you really do want only specific subreads included in your analysis for other reasons, then you will need to include all three fields in the list to use that option.

**Comment by MarisaMiller** [comment]
Hi John,
Ahh ok, that makes sense. I didn't want to just include specific subreads so I removed the -s option and it seemed to work.

However, I tried to upload the resulting xml file into the GUI with pbservice import-dataset filtered.xml --port=9091 and it says that the dataset is already present. It looks like smrtlink thinks that the subreads file that I used to filter with the whitelist, and that resulted from bam conversion of the RSII data (in pbcoretools.tasks.gather_subreadset-1/file.subreadset.xml), is the same as the filtered xml file. Perhaps something didn't work correctly with the whitelisting, or this is a different bug?

Thanks,
Marisa

**Comment by natechols** [comment]
It's a different bug - I think the whitelist needs to set a new ID for the output XML.  You can work around it by running this command (from smrtcmds/bin):

dataset newuuid filtered.xml

then import.

**Comment by jrharting** [comment]
thanks, nat.  the script is fixed so it now generates a new uuid by default

**Comment by MarisaMiller** [comment]
I just tried out the new script and it works great, no issues with uploading. One minor issue is that the whitelisted subreadset is given the name of the imported RSII movie I gave the dataset before BAM conversion (and then subsequent whitelisting of the resulting subreadset.xml file). But, that's a relatively minor issue and it's easy to see which is whitelisted due to many fewer reads.

**Comment by jrharting** [comment]
i added an option to rename the filtered dataset :)

**Comment by MarisaMiller** [comment]
I just tried it and it works great. Thanks John!
